### ISSUE TITLE
BeautifulSoup complains about a missing feature.

### ISSUE THREAD

**Issue by ugsystem** [d60/twikit#134]
I get the following error:
```python
Traceback (most recent call last):
  File "/REDACTED/scripts/get_user_tweets.py", line 38, in target
    user = client.get_user_by_screen_name(username)
  File "/REDACTED/.venv/lib/python3.10/site-packages/twikit/client.py", line 1437, in get_user_by_screen_name
    response, _ = self.get(
  File "/REDACTED/.venv/lib/python3.10/site-packages/twikit/client.py", line 169, in get
    return self.request('GET', url, **kwargs)
  File "/REDACTED/.venv/lib/python3.10/site-packages/twikit/client.py", line 134, in request
    self.unlock()
  File "/REDACTED/.venv/lib/python3.10/site-packages/twikit/client.py", line 275, in unlock
    response, html = self.captcha_solver.get_unlock_html()
  File "/REDACTED/.venv/lib/python3.10/site-packages/twikit/_captcha/base.py", line 41, in get_unlock_html
    return response, parse_unlock_html(response.text)
  File "/REDACTED/.venv/lib/python3.10/site-packages/twikit/_captcha/base.py", line 82, in parse_unlock_html
    soup = BeautifulSoup(html, 'lxml')
  File "/REDACTED/.venv/lib/python3.10/site-packages/bs4/__init__.py", line 250, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

I had to manually install `lxml` like so:
```bash
python3 -m pip install lxml
```

pip freeze:
```bash
anyio==4.4.0
beautifulsoup4==4.12.3
certifi==2024.6.2
exceptiongroup==1.2.1
filetype==1.2.0
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
idna==3.7
pyotp==2.9.0
sniffio==1.3.1
soupsieve==2.5
twikit==1.7.6
typing_extensions==4.12.2
```

**Comment by d60** [comment]
added lxml to install_requires.
