### ISSUE TITLE
Cannot import

### ISSUE THREAD

**Issue by juratjan123** [d60/twikit#175]
Having some issues and don't know why. 

```
(scraper) ➜  Python-Projects /opt/anaconda3/envs/scraper/bin/python /Users/jeffery/Python-Projects/Draft/twikit.py 
Traceback (most recent call last):
  File "/Users/jeffery/Python-Projects/Draft/twikit.py", line 1, in <module>
    from twikit import Client
  File "/Users/jeffery/Python-Projects/Draft/twikit.py", line 1, in <module>
    from twikit import Client
ImportError: cannot import name 'Client' from partially initialized module 'twikit' (most likely due to a circular import) (/Users/jeffery/Python-Projects/Draft/twikit.py)
```

**Comment by d60** [comment]
@juratjan123

**Comment by juratjan123** [comment]
> @juratjan123 Change the name of your script `twikit.py` to something else

Ohhh, thanks!! I'm so dumb, lol.
