### ISSUE TITLE
Client.login() got an unexpected keyword argument 

### ISSUE THREAD

**Issue by Moineau54** [d60/twikit#232]
Anyone know how to fix this:

```
Client.login() got an unexpected keyword argument 'username'
```

```
Traceback (most recent call last):
  File "/home/kali/Documents/Programming/twitter_tool/main.py", line 30, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/kali/Documents/Programming/twitter_tool/main.py", line 24, in main
    await client.login(
```

**Comment by Moineau54** [comment]
Fixed it. Just copy that:
```python
async def main():
    await client.login(
        auth_info_1=USERNAME ,
        auth_info_2=EMAIL,
        password=PASSWORD
    )
```
and adapt it to your needs
