### ISSUE TITLE
twikit.errors.BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

### ISSUE THREAD

**Issue by szsyzx** [d60/twikit#239]
twikit.errors.BadRequest: status: 400, message: "{"errors":[{"code":366,"message":"flow name LoginFlow is currently not accessible"}]}"

How can we completely solve it

I have seen many issues, one answer here and one answer there, but they still haven't solved the problem

**Comment by yelnats20** [comment]
try this
pip uninstall twikit

when it has uninstalled your existing package, install this fork of the repo

pip install git+https://github.com/mdmrcglu/twikit.git

as least it worked for me just now, but first make sure you uninstall the initial package

**Comment by IronEaterBeast** [comment]
> try this pip uninstall twikit
> 
> when it has uninstalled your existing package, install this fork of the repo
> 
> pip install git+https://github.com/mdmrcglu/twikit.git
> 
> as least it worked for me just now, but first make sure you uninstall the initial package

Yes, a fork can execute but the original repository cannot, which is very strange.

**Comment by yelnats20** [comment]
> > try this pip uninstall twikit
> > when it has uninstalled your existing package, install this fork of the repo
> > pip install git+https://github.com/mdmrcglu/twikit.git
> > as least it worked for me just now, but first make sure you uninstall the initial package
> 
> Yes, a fork can execute but the original repository cannot, which is very strange.

The fork fixed it, but the original repo has not updated it yet

**Comment by hirosuke0520** [comment]
I was getting the same error
`twikit.errors.BadRequest: status: 400, message:"{"errors":[{"code":366, "message": "flow name LoginFlow is currently notaccessible"}]}"`

so I tried the method in this thread.
```
pip uninstall twikit
pip install git+https://github.com/mdmrcglu/twikit.git

# I use Twikit in Lambda, so I tried it locally using python-lambda-local.(from Japan)
python-lambda-local -f lambda_handler src/lambda_function.py event.json
```
but I got a `DenyLoginSubtask` error and login fails.
[twikit/client/client.py#L391](https://github.com/mdmrcglu/twikit/blob/main/twikit/client/client.py#L391)

Here is part of my login related code 
``` python
client = Client(language='ja')
await client.login(
    auth_info_1=auth_info_1,
    auth_info_2=auth_info_2,
    password=password
)

```
If anyone knows the cause, I would appreciate it if you could share your insights.

**Comment by yelnats20** [comment]
> I was getting the same error `twikit.errors.BadRequest: status: 400, message:"{"errors":[{"code":366, "message": "flow name LoginFlow is currently notaccessible"}]}"`
> 
> so I tried the method in this thread.
> 
> ```
> pip uninstall twikit
> pip install git+https://github.com/mdmrcglu/twikit.git
> 
> # I use Twikit in Lambda, so I tried it locally using python-lambda-local.(from Japan)
> python-lambda-local -f lambda_handler src/lambda_function.py event.json
> ```
> 
> but I got a `DenyLoginSubtask` error and login fails. [twikit/client/client.py#L391](https://github.com/mdmrcglu/twikit/blob/main/twikit/client/client.py#L391)
> 
> Here is part of my login related code
> 
> ```python
> client = Client(language='ja')
> await client.login(
>     auth_info_1=auth_info_1,
>     auth_info_2=auth_info_2,
>     password=password
> )
> ```
> 
> If anyone knows the cause, I would appreciate it if you could share your insights.

try this
client = Client('en-US') 
instead of
client = Client(language='ja')

now, before you login again, ensure tour twitter account has not been banned

**Comment by hirosuke0520** [comment]
@yelnats20 
Thank you for your Immediate response!

> try this
> client = Client('en-US')
> instead of
> client = Client(language='ja')

I tried your suggestion, but I encountered the same error.

Additionally, I also tried:
・Adding an email address to the `auth_info2` property
・Using information from other Twitter accounts
However, these attempts resulted in the same error.

**Comment by SheebSuka** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by theordev** [comment]
> > try this pip uninstall twikit
> > when it has uninstalled your existing package, install this fork of the repo
> > pip install git+https://github.com/mdmrcglu/twikit.git
> > as least it worked for me just now, but first make sure you uninstall the initial package
> 
> Tried this now I get this error though:
> 
> Traceback (most recent call last): File "/Users/brandonslockey/Documents/GitHub/2024_10_30 X_Scraper_BSL/main.py", line 82, in asyncio.run(main()) File "/Users/brandonslockey/opt/anaconda3/envs/twikit-env/lib/python3.10/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/Users/brandonslockey/opt/anaconda3/envs/twikit-env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete return future.result() File "/Users/brandonslockey/Documents/GitHub/2024_10_30 X_Scraper_BSL/main.py", line 42, in main await client.login(auth_info_1=username, auth_info_2=email, password=password) File "/Users/brandonslockey/opt/anaconda3/envs/twikit-env/lib/python3.10/site-packages/twikit/client/client.py", line 391, in login if flow.task_id == 'DenyLoginSubtask': File "/Users/brandonslockey/opt/anaconda3/envs/twikit-env/lib/python3.10/site-packages/twikit/utils.py", line 103, in task_id return self.response['subtasks'][0]['subtask_id'] IndexError: list index out of range

SAME HERE ! If you got any idea about how make it work.. thanks buddy !

**Comment by datalifenyc** [comment]
# Workaround Using Browser Cookie

## Mozilla Firefox

1. Go to [https://x.com](https://x.com)
2. Log out [@userid](https://x.com/logout) (_if applicable_)
3. Press __F12__ (`Ctrl + Shift + I`) to view Web Developer Tools
4. Log into [X](https://x.com/i/flow/login)
5. Click __Storage__ tab (_towards the right_)
6. Expand __Cookies__ (_on left side_)
7. Click on `https://x.com`
8. In __Name__ column search for `auth_token` and copy the _Value_
9. In __Name__ column search for `ct0` and copy the _Value_

## `cookies.json`

1. Create a _cookies.json_ file in your project's home directory

The structure of the file should look like this:

```json
{
	"auth_token": "<your_auth_token>",
	"ct0": "<your_ct0>"
}
```

## Example Python File

`main.py`

```python
# Built-in Libraries
import asyncio

# Third-Party Libraries
from twikit import Client

# Initialize client

client = Client(
    language = 'en-US',
)

async def main():
    client.load_cookies('cookies.json')

    # Get news trends
    trends = await client.get_trends('news')
    for trend in trends:
        print(trend)

asyncio.run(main())
```

## Output

```
<Trend name="The S&P 500">
<Trend name="Mac mini">
<Trend name="$TSLA">
<Trend name="Strategic Bitcoin Reserve">
<Trend name="BNB Chain">
<Trend name="#opensource">
<Trend name="Patents">
<Trend name="NEW ALL TIME HIGH">
<Trend name="Dextools">
<Trend name="$ADA">
<Trend name="BlackRock's Bitcoin ETF">
<Trend name="Molly">
<Trend name="#GROK">
<Trend name="#RollTide">
<Trend name="$BABA">
<Trend name="Gold ETF">
<Trend name="Tom Lee">
<Trend name="Utah">
<Trend name="$ATOM">
```


 
## References

[load_cookies(path: str) → None](https://twikit.readthedocs.io/en/latest/twikit.html#twikit.client.client.Client.load_cookies)

[twikit/examples/examples.py](https://github.com/d60/twikit/blob/f2658402d93a2bb0050e1ceea3c6cbaf0053ba41/examples/example.py)

**Comment by d60** [comment]
try version 2.2.0
