### ISSUE TITLE
Support of delegated account?

### ISSUE THREAD

**Issue by ivanfong01** [d60/twikit#54]
It is possible to add support for using delegated account to post tweets?

**Comment by d60** [comment]
@ivanfong01 Added `set_delegate_account` in version 1.4.3

Example
```python
client.set_delegate_account('00000000000')
client.create_tweet('Hello, World')  # Tweet as user 00000000000

client.set_delegate_account(None)    # Revert back to the original user
```

**Comment by degenwarsdali** [comment]
I get an error when trying to peroform any action

e.g
2024-06-12 06:51:15.616 | ERROR    | __main__:main:53 - Failed to set delegated account: 
 status: 403, message: "{"errors":[{"message":"Contributor access is not permitted on this endpoint","code":90}]}
"
Traceback (most recent call last):
  File "c:\Users\hp\Documents\degenwars\CODE\RPG_discord_bot-main\RPG_discord_bot-main\utils\xcom.py", line 48, in main
    user =  await client.user()
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\.conda\envs\xp_bot\Lib\site-packages\twikit\twikit_async\client.py", line 492, in user
    return await self.get_user_by_id(await self.user_id())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\.conda\envs\xp_bot\Lib\site-packages\twikit\twikit_async\client.py", line 1516, in get_user_by_id
    response, _ = await self.get(
                  ^^^^^^^^^^^^^^^
  File "C:\Users\hp\.conda\envs\xp_bot\Lib\site-packages\twikit\twikit_async\client.py", line 170, in get
    return await self.request('GET', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\.conda\envs\xp_bot\Lib\site-packages\twikit\twikit_async\client.py", line 153, in request
    raise Forbidden(message, headers=response.headers)
twikit.errors.Forbidden: status: 403, message: "{"errors":[{"message":"Contributor access is not permitted on this endpoint","code":90}]}
"
