### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by PayneXie** [d60/twikit#72]
`from twikit import Client`

`Traceback (most recent call last):
  File "/Users/paynexie/FollowStatsCollector/test.py", line 1, in <module>
    from twikit import Client
  File "/Users/paynexie/FollowStatsCollector/venv/lib/python3.9/site-packages/twikit/__init__.py", line 9, in <module>
    from .client import Client
  File "/Users/paynexie/FollowStatsCollector/venv/lib/python3.9/site-packages/twikit/client.py", line 12, in <module>
    from .errors import (
  File "/Users/paynexie/FollowStatsCollector/venv/lib/python3.9/site-packages/twikit/errors.py", line 31, in <module>
    class TooManyRequests(TwitterException):
  File "/Users/paynexie/FollowStatsCollector/venv/lib/python3.9/site-packages/twikit/errors.py", line 35, in TooManyRequests
    def __init__(self, *args, headers: dict | None = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`

**Comment by d60** [comment]
Use Python version 3.10 or above, or insert `from __future__ import annontations` at the top of `twikit/errors.py`.

**Comment by ashutoshChant** [comment]
this did not work
