### ISSUE TITLE
get_trends() easily got KeyError 'trend' when using category other than trending

### ISSUE THREAD

**Issue by CocoaRush** [d60/twikit#91]
the error: 
File "/usr/local/lib/python3.10/site-packages/twikit/client.py", line 2582, in get_trends
`trend_info = item['item']['content']['trend']`

I am wondering if some item may not have the key `trend`, it may need to do a key existing test, and only valid `trend_info` could be added to results.

**Comment by d60** [comment]
can't reproduce.

**Comment by ultravigilante** [comment]
Hello, I'm experiencing this issue when using:

```py
trends = await client.get_trends('for-you')
trends = await client.get_trends('sports')
```

`'trending'`, `'entertainment'` and `'news'` are working for me.

I checked in the Twitter UI and I have feeds for them all, but I see this when calling from twikit:

```
$ python main.py
Traceback (most recent call last):
  File "/home/me/repos/work/trending-test/main.py", line 24, in <module>
    asyncio.run(main())
  File "/home/me/.local/share/mise/installs/python/3.11.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/me/.local/share/mise/installs/python/3.11.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.local/share/mise/installs/python/3.11.11/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/me/repos/work/trending-test/main.py", line 21, in main
    trending = await client.get_trends('sports')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/repos/work/trending-test/venv/lib/python3.11/site-packages/twikit/client/client.py", line 2561, in get_trends
    trend_info = item['item']['content']['trend']
                 ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'trend'
```

System details:

```
Python version: 3.11.11
OS: Pop_OS! 22.04 LTS
Library version: latest (2.2.0)
```

Cheers

**Comment by ultravigilante** [comment]
Without any changes, I tested it on a different X account (one that looks less like a bot) and it worked. Probably account related.
